# fly.toml app configuration file generated for n8n-oneway-bike on 2024-11-15T16:53:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flyn8nqwik'
primary_region = 'ams'

[build]
  image = 'n8nio/n8n'

[env]
  EXECUTIONS_DATA_MAX_AGE = '168'
  EXECUTIONS_DATA_PRUNE = 'true'
  EXECUTIONS_DATA_PRUNE_MAX_COUNT = '10000'
  GENERIC_TIMEZONE = 'Europe/Amsterdam'
  N8N_CUSTOM_EXTENSIONS = '/home/node/.n8n/customnodes'
  N8N_DIAGNOSTICS_ENABLED = 'false'
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS = 'true'
  N8N_HIRING_BANNER_ENABLED = 'false'
  N8N_HOST = 'flyn8nqwik.fly.dev'
  N8N_PORT = '8080'
  N8N_PROTOCOL = 'https'
  NODE_FUNCTION_ALLOW_EXTERNAL = 'true'
  TINI_SUBREAPER = 'true'
  WEBHOOK_URL = 'https://flyn8nqwik.fly.dev'

[[mounts]]
  source = 'n8n_vol'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

[[files]]
  guest_path = '/home/node/n8n-nodes-n8nergonode-0.1.0.tgz'
  local_path = 'n8n-nodes-n8nergonode-0.1.0.tgz'

[[files]]
  guest_path = '/home/node/build.sh'
  local_path = 'build.sh'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
