# fly.toml app configuration file generated for onewayservice on 2024-11-21T07:08:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'onewayservice'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NODE_VERSION = "20"
    N8N_VERSION = "1.68.0"

[env]
  EXECUTIONS_DATA_MAX_AGE = '168'
  EXECUTIONS_DATA_PRUNE = 'true'
  EXECUTIONS_DATA_PRUNE_MAX_COUNT = '10000'
  GENERIC_TIMEZONE = 'Europe/Amsterdam'
  N8N_CUSTOM_EXTENSIONS = '/home/node/.n8n/customnodes'
  N8N_DIAGNOSTICS_ENABLED = 'false'
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS = 'true'
  N8N_HIRING_BANNER_ENABLED = 'false'
  N8N_HOST = '0.0.0.0'
  N8N_PORT = '8080'
  N8N_PROTOCOL = 'https'
  NODE_FUNCTION_ALLOW_EXTERNAL = 'true'
  TINI_SUBREAPER = 'true'
  WEBHOOK_URL = 'https://onewayservice.fly.dev/n8n'
  N8N_PATH = '/n8n'
  N8N_WEBHOOK_TUNNEL_URL = 'https://onewayservice.fly.dev/n8n'
  N8N_ENDPOINT_REST = '/n8n'
  N8N_ENDPOINT_WEBHOOK = '/n8n/webhook'
  N8N_ENDPOINT_WEBHOOK_TEST = '/n8n/webhook-test'

[[mounts]]
  source = 'n8n_vol'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

[[files]]
  guest_path = '/home/node/n8n-nodes-n8nergonode-0.1.0.tgz'
  local_path = 'n8n-nodes-n8nergonode-0.1.0.tgz'

[[files]]
  guest_path = '/home/node/build.sh'
  local_path = 'build.sh'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
