name: Fly Deploy
on:
  push:
    branches:
      - master    # change to main if needed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: FlyV1 fm2_lJPECAAAAAAAB9WcxBAfRYnfJm8ZLveD1CuBlk5OwrVodHRwczovL2FwaS5mbHkuaW8vdjGUAJLOAA1MEh8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDyo/fvPJkaEIuF3DnG1k/8kBxbkCzqzGZEgYrZSP9xCgp8YDbrjeU1KYsDUqnQGMDKxK80z4ecl3JPbXkPETlOo2CzP/qUEyT08UmR8l0kSGaN5ruLO829436R4/BjcSxbetvZIr5YwygwEERqNsVvc6KjTOS1cU7jmcS1DTic0bMiKperJbghSigFrYcQgG51LQonG8gyWI+hVrRmjmG4ciwFN8UuaOkEUY9BD/o4=,fm2_lJPETlOo2CzP/qUEyT08UmR8l0kSGaN5ruLO829436R4/BjcSxbetvZIr5YwygwEERqNsVvc6KjTOS1cU7jmcS1DTic0bMiKperJbghSigFrYcQQB6WmB2op4KUzsBcK6UVFZsO5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5nMLiUzwAAAAEjKNayF84AC0mWCpHOAAtJlgzEEOkbL7xHgzO4/qIq0/kLlbTEIGHW7gSiM+Fbffg5GFkSWAkv+uU14xnEpbfJkuHXolhY
